steps:
  # Build the Docker image.
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/gcp-host-ssr:$SHORT_SHA', '.']
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/gcp-host-ssr:$SHORT_SHA']
  # Deploy to Cloud Run
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['beta', 'run', 'deploy', 'gcp-host-ssr', '--image=eu.gcr.io/$PROJECT_ID/gcp-host-ssr:$SHORT_SHA', '--region=europe-west1']
  # Deploy to Firebase Platform
  # - name: gcr.io/$PROJECT_ID/firebase
  #   args: ['deploy', '--project=$PROJECT_ID', '--only=hosting']